name: IO:Enso
description: IO:Enso (Enso Okame). <br/> Ğ’ĞµĞ±-Ñ€Ğ°Ğ·Ñ€Ğ°Ğ±Ğ¾Ñ‚Ñ‡Ğ¸Ğº / ĞºĞ¾Ğ´ĞµÑ€ / Ğ³Ñ€Ğ°Ñ„Ğ¸Ñ‡ĞµÑĞºĞ¸Ğ¹ Ğ´Ğ¸Ğ·Ğ°Ğ¹Ğ½ĞµÑ€. ğŸ‘¨â€ğŸ’» <br/>P.S. Â«Enso OkameÂ» ÑÑ‚Ğ¾ Ğ²ÑĞµĞ³Ğ¾-Ğ»Ğ¸ÑˆÑŒ Ğ¿ÑĞµĞ²Ğ´Ğ¾Ğ½Ğ¸Ğ¼ ğŸ±
dtitle: Ğ¢Ğ¸Ñ…Ğ¸Ğ¹ ÑƒĞ³Ğ¾Ğ»Ğ¾Ğº ĞºĞ¾Ñ‚Ğ°-ĞºĞ¾Ğ´ĞµÑ€Ğ° ğŸ±

avatar: /assets/img/me_1.jpg

footer-links:
  dribbble:
  email:
  vk:
  facebook:
  
disqus:

google_analytics:

url:
baseurl: ""
excerpt_separator: <!--more-->
permalink: /:year/:month/:day/:title.html

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: :expanded

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
