name: Økame

description: Веб разработчик (☺)

avatar: http://ioenso.github.io/assets/img/avatar.jpg

footer-links:
  dribbble:
  email:
  vk:
  facebook:
  
disqus:

google_analytics:

url:
baseurl: ""
excerpt_separator: <!--more-->
permalink: /:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: :expanded

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
