name: IO:Enso
description: IO:Enso (Enso Okame).<br/>–í–µ–±-—Ä–∞–∑—Ä–∞–±–æ—Ç—á–∏–∫ / –∫–æ–¥–µ—Ä / –≥—Ä–∞—Ñ–∏—á–µ—Å–∫–∏–π –¥–∏–∑–∞–π–Ω–µ—Ä üíªüê±<br/>
dtitle: –¢–∏—Ö–∏–π —É–≥–æ–ª–æ–∫ –∫–æ—Ç–∞-–∫–æ–¥–µ—Ä–∞ üê±

avatar: https://avatars0.githubusercontent.com/u/17423646?v=4&u=bd2679fc5870dac9f39ab1bdcbce47f002ace21c&s=400

footer-links:
  dribbble:
  email:
  vk:
  facebook:
  
disqus:

google_analytics:

url:
baseurl: ""
excerpt_separator: <!--more-->

# Site settings
permalink: pretty

# Pages permalink
defaults:
  -
    scope:
      type: "pages"
    values:
      permalink: /:path/:basename:output_ext

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: :expanded

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
